-- MySQL Script generated by MySQL Workbench
-- Sun Sep 21 12:12:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ORDEM DE SERVIÇO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDEM DE SERVIÇO` (
  `idORDEM DE SERVIÇO` INT NOT NULL,
  `DATA_EMISSAO` DATE NULL,
  `VALOR` DECIMAL(10,2) NULL,
  `STATUS` VARCHAR(45) NULL,
  `DATA_CONCLUSAO` DATE NULL,
  PRIMARY KEY (`idORDEM DE SERVIÇO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VEICULO` (
  `idVEICULO` INT NOT NULL,
  `MODELO` VARCHAR(45) NULL,
  `ANO` INT NULL,
  `PLACA` VARCHAR(45) NULL,
  `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` INT NOT NULL,
  PRIMARY KEY (`idVEICULO`, `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`),
  INDEX `fk_VEICULO_ORDEM DE SERVIÇO1_idx` (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULO_ORDEM DE SERVIÇO1`
    FOREIGN KEY (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`)
    REFERENCES `mydb`.`ORDEM DE SERVIÇO` (`idORDEM DE SERVIÇO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `CONTATO` VARCHAR(45) NULL,
  `VEICULO_idVEICULO` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`, `VEICULO_idVEICULO`),
  INDEX `fk_CLIENTE_VEICULO_idx` (`VEICULO_idVEICULO` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_VEICULO`
    FOREIGN KEY (`VEICULO_idVEICULO`)
    REFERENCES `mydb`.`VEICULO` (`idVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MECANICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MECANICOS` (
  `idMECANICOS` INT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `ENDEREÇO` VARCHAR(45) NULL,
  `ESPECIALIDADE` VARCHAR(45) NULL,
  `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` INT NOT NULL,
  PRIMARY KEY (`idMECANICOS`, `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`),
  INDEX `fk_MECANICOS_ORDEM DE SERVIÇO1_idx` (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` ASC) VISIBLE,
  CONSTRAINT `fk_MECANICOS_ORDEM DE SERVIÇO1`
    FOREIGN KEY (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`)
    REFERENCES `mydb`.`ORDEM DE SERVIÇO` (`idORDEM DE SERVIÇO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVIÇO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVIÇO` (
  `idSERVIÇO` INT NOT NULL,
  `DESCRICAO` VARCHAR(45) NULL,
  `VALOR_MAODEOBRA` DECIMAL(10,2) NULL,
  `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` INT NOT NULL,
  PRIMARY KEY (`idSERVIÇO`, `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`),
  INDEX `fk_SERVIÇO_ORDEM DE SERVIÇO1_idx` (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` ASC) VISIBLE,
  CONSTRAINT `fk_SERVIÇO_ORDEM DE SERVIÇO1`
    FOREIGN KEY (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`)
    REFERENCES `mydb`.`ORDEM DE SERVIÇO` (`idORDEM DE SERVIÇO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEÇAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEÇAS` (
  `idPEÇAS` INT NOT NULL,
  `NOME_PECA` VARCHAR(45) NULL,
  `VALOR` DECIMAL(10,2) NULL,
  `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` INT NOT NULL,
  PRIMARY KEY (`idPEÇAS`, `ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`),
  INDEX `fk_PEÇAS_ORDEM DE SERVIÇO1_idx` (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO` ASC) VISIBLE,
  CONSTRAINT `fk_PEÇAS_ORDEM DE SERVIÇO1`
    FOREIGN KEY (`ORDEM DE SERVIÇO_idORDEM DE SERVIÇO`)
    REFERENCES `mydb`.`ORDEM DE SERVIÇO` (`idORDEM DE SERVIÇO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
